const websites = [
    {"name": "Neal.fun", "url": "https://neal.fun/", "rating": "sfw"},
    {"name": "The Useless Web", "url": "https://theuselessweb.com/", "rating": "sfw"},
    {"name": "Bored Button", "url": "https://www.boredbutton.com/", "rating": "sfw"},
    {"name": "Pointer Pointer", "url": "https://pointerpointer.com/", "rating": "sfw"},
    {"name": "Find the Invisible Cow", "url": "https://findtheinvisiblecow.com/", "rating": "sfw"},
    {"name": "Akinator", "url": "https://en.akinator.com/", "rating": "sfw"},
    {"name": "Zoomquilt 2", "url": "https://zoomquilt2.madmindworx.com/", "rating": "sfw"},
    {"name": "Koalas to the Max", "url": "https://koalastothemax.com/", "rating": "sfw"},
    {"name": "Typatone", "url": "https://typatone.com/", "rating": "sfw"},
    {"name": "Radio Garden", "url": "https://radio.garden/", "rating": "sfw"},
    {"name": "Window Swap", "url": "https://www.window-swap.com/", "rating": "sfw"},
    {"name": "Quick Draw", "url": "https://quickdraw.withgoogle.com/", "rating": "sfw"},
    {"name": "Paper Toilet", "url": "https://papertoilet.com/", "rating": "sfw"},
    {"name": "Z0r", "url": "https://z0r.de/", "rating": "sfw"},
    {"name": "Procatinator", "url": "https://procatinator.com/", "rating": "sfw"},
    {"name": "7 Billion World", "url": "https://www.7billionworld.com/", "rating": "sfw"},
    {"name": "Electric Boogie Woogie", "url": "https://www.electricboogiewoogie.com/", "rating": "sfw"},
    {"name": "Endless Horse", "url": "https://endless.horse/", "rating": "sfw"},
    {"name": "Falling Falling", "url": "https://fallingfalling.com/", "rating": "sfw"},
    {"name": "Staggering Beauty", "url": "https://www.staggeringbeauty.com/", "rating": "sfw"},
    {"name": "Bouncing DVD Logo", "url": "https://bouncingdvdlogo.com/", "rating": "sfw"},
    {"name": "Oimo", "url": "https://oimo.io/", "rating": "sfw"},
    {"name": "Mr.doob Ball Pool", "url": "https://mrdoob.com/projects/chromeexperiments/ball-pool/", "rating": "sfw"},
    {"name": "Wiby", "url": "https://wiby.me/", "rating": "sfw"},
    {"name": "GifCities", "url": "https://gifcities.org/", "rating": "sfw"},
    {"name": "Scale of the Universe", "url": "https://htwins.net/scale2/scale2.html", "rating": "sfw"},
    {"name": "Earth Nullschool", "url": "https://earth.nullschool.net/", "rating": "sfw"},
    {"name": "100,000 Stars", "url": "https://stars.chromeexperiments.com/", "rating": "sfw"},
    {"name": "Lightning Maps", "url": "https://www.lightningmaps.org/", "rating": "sfw"},
    {"name": "OneZoom", "url": "https://www.onezoom.org/", "rating": "sfw"},
    {"name": "Stellarium Web", "url": "https://stellarium-web.org/", "rating": "sfw"},
    {"name": "Fake Update", "url": "https://fakeupdate.net/", "rating": "sfw"},
    {"name": "GeekTyper", "url": "https://geektyper.com/", "rating": "sfw"},
    {"name": "Pranx", "url": "https://pranx.com/", "rating": "sfw"},
    {"name": "Semantris", "url": "https://research.google.com/semantris/", "rating": "sfw"},
    {"name": "This Word Does Not Exist", "url": "https://www.thisworddoesnotexist.com/", "rating": "sfw"},
    {"name": "This Graffiti Does Not Exist", "url": "https://thisgraffitidoesnotexist.com/", "rating": "sfw"},
    {"name": "This Automobile Does Not Exist", "url": "https://www.thisautomobiledoesnotexist.com/", "rating": "sfw"},
    {"name": "This Campsite Does Not Exist", "url": "https://thiscampsitedoesnotexist.com/", "rating": "sfw"},
    {"name": "This Mountain Does Not Exist", "url": "https://thismountaindoesnotexist.com/", "rating": "sfw"},
    {"name": "Your AI Slop Bores Me", "url": "https://youraislopbores.me/", "rating": "sfw"},
    {"name": "AutoDraw", "url": "https://www.autodraw.com/", "rating": "sfw"},
    {"name": "Perchance", "url": "https://perchance.org/", "rating": "sfw"},
    {"name": "Dino Pal", "url": "https://dino-chrome.com/", "rating": "sfw"},
    {"name": "Gradient Horse", "url": "https://gradient.horse/", "rating": "sfw"},
    {"name": "Monkeys.zip", "url": "https://monkeys.zip/", "rating": "sfw"},
    {"name": "Everyone Draw", "url": "https://everyonedraw.com/", "rating": "sfw"},
    {"name": "Wplace", "url": "https://wplace.live/", "rating": "sfw"},
    {"name": "Multiplayer Piano", "url": "https://multiplayerpiano.com/", "rating": "sfw"},
    {"name": "PixelCanvas", "url": "https://pixelcanvas.io/", "rating": "sfw"},
    {"name": "Flag Click", "url": "https://flagclick.com/", "rating": "sfw"},
    {"name": "Hallucinate", "url": "https://hallucinate.site/", "rating": "sfw"},
    {"name": "Cloudhiker", "url": "https://cloudhiker.net/", "rating": "sfw"},
    {"name": "Click the Red Button", "url": "https://clicktheredbutton.com/", "rating": "sfw"},
    {"name": "IMG_0001", "url": "https://walzr.com/IMG_0001/", "rating": "sfw"},
    {"name": "Random Street View", "url": "https://randomstreetview.com/", "rating": "sfw"},
    {"name": "Not a Robot", "url": "https://notarobot.org/", "rating": "sfw"},
    {"name": "Make Everything OK", "url": "https://make-everything-ok.com/", "rating": "sfw"},
    {"name": "1000 Awesome Things", "url": "https://1000awesomethings.com/", "rating": "sfw"},
    {"name": "Digibouquet", "url": "https://digi.pauwee.com/", "rating": "sfw"},
    {"name": "Happy Broadcast", "url": "https://www.thehappybroadcast.com/", "rating": "sfw"},
    {"name": "Popcat", "url": "https://popcat.click/", "rating": "sfw"},
    {"name": "Nyan Cat", "url": "https://www.nyan.cat/", "rating": "sfw"},
    {"name": "Bongo Cat", "url": "https://bongo.cat/", "rating": "sfw"},
    {"name": "Meow Camera", "url": "https://meow.camera/", "rating": "sfw"},
    {"name": "Doughnut Kitten", "url": "https://doughnutkitten.com/", "rating": "sfw"},
    {"name": "It's Raining Cat", "url": "https://itsrainingcat.fun/", "rating": "sfw"},
    {"name": "Do Nothing for 2 Minutes", "url": "https://www.donothingfor2minutes.org/", "rating": "sfw"},
    {"name": "Slow Roads", "url": "https://slowroads.io/", "rating": "sfw"},
    {"name": "Adrift", "url": "https://adrift.today/", "rating": "sfw"},
    {"name": "Rainyscope", "url": "https://rainyscope.com/", "rating": "sfw"},
    {"name": "Ambient Garden", "url": "https://ambient.garden/", "rating": "sfw"},
    {"name": "Pixel Thoughts", "url": "https://www.pixelthoughts.co/", "rating": "sfw"},
    {"name": "Firewood Splitting Simulator", "url": "https://screen.toys/", "rating": "sfw"},
    {"name": "Scratch Art", "url": "https://paint.toys/", "rating": "sfw"},
    {"name": "Bouncy Balls", "url": "https://bouncyballs.org/", "rating": "sfw"},
    {"name": "Mandalagaba", "url": "https://www.mandalagaba.com/", "rating": "sfw"},
    {"name": "David Li Web Toys", "url": "https://david.li/", "rating": "sfw"},
    {"name": "Particle Love", "url": "https://particle-love.com/", "rating": "sfw"},
    {"name": "Zen Photon Garden", "url": "https://zenphoton.com/", "rating": "sfw"},
    {"name": "GPU Fluid Experiments", "url": "https://haxiomic.github.io/GPU-Fluid-Experiments/html5/", "rating": "sfw"},
    {"name": "Can't Unsee", "url": "https://cantunsee.space/", "rating": "sfw"},
    {"name": "Color GeoGuessr", "url": "https://color-geo-guesser.mohit.rocks/", "rating": "sfw"},
    {"name": "Pixactly", "url": "https://pixactly.app/", "rating": "sfw"},
    {"name": "The Boolean Game", "url": "https://boolean.method.ac/", "rating": "sfw"},
    {"name": "Kern Type", "url": "https://type.method.ac/", "rating": "sfw"},
    {"name": "Shape Type", "url": "https://shape.method.ac/", "rating": "sfw"},
    {"name": "It's Centred That", "url": "https://avark.agency/", "rating": "sfw"},
    {"name": "Boring Balls", "url": "https://boringballs.com/", "rating": "sfw"},
    {"name": "VOL E.wtf", "url": "https://vole.wtf/", "rating": "sfw"},
    {"name": "Pointless Sites", "url": "https://pointlesssites.com/", "rating": "sfw"},
    {"name": "Pippin Barr Games", "url": "https://pippinbarr.com/", "rating": "sfw"},
    {"name": "aSoftMurmur", "url": "https://asoftmurmur.com/", "rating": "sfw"},
    {"name": "Rainy Mood", "url": "https://www.rainymood.com/", "rating": "sfw"},
    {"name": "Noisli", "url": "https://www.noisli.com/", "rating": "sfw"},
    {"name": "Lofi Cafe", "url": "https://lofi.cafe/", "rating": "sfw"},
    {"name": "Poolside FM", "url": "https://poolside.fm/", "rating": "sfw"},
    {"name": "Radiooooo", "url": "https://radiooooo.com/", "rating": "sfw"},
    {"name": "Nightride FM", "url": "https://nightride.fm/", "rating": "sfw"},
    {"name": "Lofi Girl", "url": "https://www.lofigirl.com/", "rating": "sfw"},
    {"name": "SomaFM", "url": "https://somafm.com/", "rating": "sfw"},
    {"name": "NTS Radio", "url": "https://www.nts.live/", "rating": "sfw"},
    {"name": "Boiler Room", "url": "https://boilerroom.tv/", "rating": "sfw"},
    {"name": "Incredibox", "url": "https://www.incredibox.com/", "rating": "sfw"},
    {"name": "Chrome Music Lab", "url": "https://musiclab.chromeexperiments.com/", "rating": "sfw"},
    {"name": "Typedrummer", "url": "https://typedrummer.com/", "rating": "sfw"},
    {"name": "Touch Pianist", "url": "https://touchpianist.com/", "rating": "sfw"},
    {"name": "Online Sequencer", "url": "https://onlinesequencer.net/", "rating": "sfw"},
    {"name": "ButtonBass", "url": "https://www.buttonbass.com/", "rating": "sfw"},
    {"name": "Gnoosic", "url": "https://www.gnoosic.com/", "rating": "sfw"},
    {"name": "Chess.com", "url": "https://www.chess.com/", "rating": "sfw"},
    {"name": "Board Game Arena", "url": "https://boardgamearena.com/", "rating": "sfw"},
    {"name": "GeoGuessr", "url": "https://www.geoguessr.com/", "rating": "sfw"},
    {"name": "Skribbl.io", "url": "https://skribbl.io/", "rating": "sfw"},
    {"name": "Gartic Phone", "url": "https://garticphone.com/", "rating": "sfw"},
    {"name": "Tetr.io", "url": "https://tetr.io/", "rating": "sfw"},
    {"name": "Slither.io", "url": "https://slither.io/", "rating": "sfw"},
    {"name": "Agar.io", "url": "https://agar.io/", "rating": "sfw"},
    {"name": "Diep.io", "url": "https://diep.io/", "rating": "sfw"},
    {"name": "Paper.io", "url": "https://paper-io.com/", "rating": "sfw"},
    {"name": "Shell Shockers", "url": "https://shellshock.io/", "rating": "sfw"},
    {"name": "OpenFront", "url": "https://openfront.io/", "rating": "sfw"},
    {"name": "Narrow One", "url": "https://narrow.one/", "rating": "sfw"},
    {"name": "Voxiom", "url": "https://voxiom.io/", "rating": "sfw"},
    {"name": "Kour.io", "url": "https://kour.io/", "rating": "sfw"},
    {"name": "Repuls.io", "url": "https://repuls.io/", "rating": "sfw"},
    {"name": "EvoWorld.io", "url": "https://evoworld.io/", "rating": "sfw"},
    {"name": "Moomoo.io", "url": "https://moomoo.io/", "rating": "sfw"},
    {"name": "HaxBall", "url": "https://www.haxball.com/", "rating": "sfw"},
    {"name": "CrazyGames", "url": "https://www.crazygames.com/", "rating": "sfw"},
    {"name": "Poki", "url": "https://poki.com/", "rating": "sfw"},
    {"name": "Newgrounds", "url": "https://www.newgrounds.com/", "rating": "sfw"},
    {"name": "Armor Games", "url": "https://armorgames.com/", "rating": "sfw"},
    {"name": "Kongregate", "url": "https://www.kongregate.com/", "rating": "sfw"},
    {"name": "Addicting Games", "url": "https://www.addictinggames.com/", "rating": "sfw"},
    {"name": "Coolmath Games", "url": "https://www.coolmathgames.com/", "rating": "sfw"},
    {"name": "Miniclip", "url": "https://www.miniclip.com/", "rating": "sfw"},
    {"name": "Pogo", "url": "https://www.pogo.com/", "rating": "sfw"},
    {"name": "Game Jolt", "url": "https://gamejolt.com/", "rating": "sfw"},
    {"name": "Jay is Games", "url": "https://jayisgames.com/", "rating": "sfw"},
    {"name": "IndieGames", "url": "https://indiegames.com/", "rating": "sfw"},
    {"name": "Kizi", "url": "https://kizi.com/", "rating": "sfw"},
    {"name": "Nitrome", "url": "https://www.nitrome.com/", "rating": "sfw"},
    {"name": "Flashpoint Archive", "url": "https://flashpointarchive.org/", "rating": "sfw"},
    {"name": "Internet Archive Software", "url": "https://archive.org/details/software", "rating": "sfw"},
    {"name": "DOS Games Archive", "url": "https://www.dosgamesarchive.com/", "rating": "sfw"},
    {"name": "My Abandonware", "url": "https://www.myabandonware.com/", "rating": "sfw"},
    {"name": "PlayClassicGames", "url": "https://playclassic.games/", "rating": "sfw"},
    {"name": "The Strong National Museum of Play", "url": "https://www.museumofplay.org/", "rating": "sfw"},
    {"name": "MAME", "url": "https://www.mamedev.org/", "rating": "sfw"},
    {"name": "PICO-8", "url": "https://www.lexaloffle.com/pico-8.php", "rating": "sfw"},
    {"name": "Pico Park", "url": "https://picopark.com/", "rating": "sfw"},
    {"name": "Universal Paperclips", "url": "https://www.decisionproblem.com/paperclips/index2.html", "rating": "sfw"},
    {"name": "A Dark Room", "url": "https://adarkroom.doublespeakgames.com/", "rating": "sfw"},
    {"name": "Cookie Clicker", "url": "https://orteil.dashnet.org/cookieclicker/", "rating": "sfw"},
    {"name": "Antimatter Dimensions", "url": "https://ivark.github.io/", "rating": "sfw"},
    {"name": "Realm Grinder", "url": "https://www.divinegames.it/", "rating": "sfw"},
    {"name": "Hextris", "url": "https://hextris.io/", "rating": "sfw"},
    {"name": "2048", "url": "https://2048.org/", "rating": "sfw"},
    {"name": "Tetris", "url": "https://tetris.com/", "rating": "sfw"},
    {"name": "Jigsaw Puzzles", "url": "https://www.jigsawexplorer.com/", "rating": "sfw"},
    {"name": "Sudoku.com", "url": "https://sudoku.com/", "rating": "sfw"},
    {"name": "Daily Sudoku", "url": "https://sudoku.coach/", "rating": "sfw"},
    {"name": "Minesweeper Online", "url": "https://minesweeper.online/", "rating": "sfw"},
    {"name": "Solitaired", "url": "https://solitaired.com/", "rating": "sfw"},
    {"name": "FreeCell", "url": "https://www.freecell.io/", "rating": "sfw"},
    {"name": "Spider Solitaire", "url": "https://www.spider-solitaire-challenge.com/", "rating": "sfw"},
    {"name": "Mahjong", "url": "https://www.mahjongfun.com/", "rating": "sfw"},
    {"name": "Checkers", "url": "https://www.playok.com/en/checkers/", "rating": "sfw"},
    {"name": "Backgammon Galaxy", "url": "https://www.backgammongalaxy.com/", "rating": "sfw"},
    {"name": "Free Games", "url": "https://www.puzzles.org/", "rating": "sfw"},
    {"name": "Sporcle", "url": "https://www.sporcle.com/", "rating": "sfw"},
    {"name": "JetPunk", "url": "https://www.jetpunk.com/", "rating": "sfw"},
    {"name": "Kahoot", "url": "https://kahoot.com/", "rating": "sfw"},
    {"name": "Blooket", "url": "https://www.blooket.com/", "rating": "sfw"},
    {"name": "Gimkit", "url": "https://www.gimkit.com/", "rating": "sfw"},
    {"name": "Murdle", "url": "https://murdle.com/", "rating": "sfw"},
    {"name": "Clues by Sam", "url": "https://cluesbysam.com/", "rating": "sfw"},
    {"name": "Contexto", "url": "https://www.contexto.me/", "rating": "sfw"},
    {"name": "Quordle", "url": "https://www.quordle.com/", "rating": "sfw"},
    {"name": "Waffle Game", "url": "https://wafflegame.net/", "rating": "sfw"},
    {"name": "Duotrigordle", "url": "https://duotrigordle.com/", "rating": "sfw"},
    {"name": "Wardle", "url": "https://wardlegame.com/", "rating": "sfw"},
    {"name": "Ba Ba Dum", "url": "https://babadum.com/", "rating": "sfw"},
    {"name": "Semantle", "url": "https://semantle.com/", "rating": "sfw"},
    {"name": "Framed", "url": "https://framed.wtf/", "rating": "sfw"},
    {"name": "Wordle", "url": "https://www.nytimes.com/games/wordle/index.html", "rating": "sfw"},
    {"name": "Connections", "url": "https://www.nytimes.com/games/connections", "rating": "sfw"},
    {"name": "Mini Crossword", "url": "https://www.nytimes.com/crosswords/game/mini", "rating": "sfw"},
    {"name": "Worldle", "url": "https://worldle.teuteuf.fr/", "rating": "sfw"},
    {"name": "Globle", "url": "https://globle-game.com/", "rating": "sfw"},
    {"name": "City Guesser", "url": "https://cityguesser.eu/", "rating": "sfw"},
    {"name": "GeoTastic", "url": "https://geotastic.net/", "rating": "sfw"},
    {"name": "Metazooa", "url": "https://metazooa.com/", "rating": "sfw"},
    {"name": "Guess the Correlation", "url": "https://guessthecorrelation.com/", "rating": "sfw"},
    {"name": "Human Benchmark", "url": "https://humanbenchmark.com/", "rating": "sfw"},
    {"name": "10FastFingers", "url": "https://10fastfingers.com/", "rating": "sfw"},
    {"name": "TypeRacer", "url": "https://play.typeracer.com/", "rating": "sfw"},
    {"name": "Monkeytype", "url": "https://monkeytype.com/", "rating": "sfw"},
    {"name": "TypeLit", "url": "https://www.typelit.io/", "rating": "sfw"},
    {"name": "Typing.io", "url": "https://typing.io/", "rating": "sfw"},
    {"name": "TypingClub", "url": "https://www.typingclub.com/", "rating": "sfw"},
    {"name": "Vim Adventures", "url": "https://vim-adventures.com/", "rating": "sfw"},
    {"name": "Flexbox Froggy", "url": "https://flexboxfroggy.com/", "rating": "sfw"},
    {"name": "Grid Garden", "url": "https://cssgridgarden.com/", "rating": "sfw"},
    {"name": "The Git Game", "url": "https://www.git-game.com/", "rating": "sfw"},
    {"name": "SQL Murder Mystery", "url": "https://mystery.knightlabprojects.com/", "rating": "sfw"},
    {"name": "Regex Crossword", "url": "https://regexcrossword.com/", "rating": "sfw"},
    {"name": "Battle for Wesnoth", "url": "https://www.wesnoth.org/", "rating": "sfw"},
    {"name": "OpenRCT2", "url": "https://openrct2.org/", "rating": "sfw"},
    {"name": "Minetest", "url": "https://www.minetest.net/", "rating": "sfw"},
    {"name": "Unciv", "url": "https://yairm210.github.io/Unciv/", "rating": "sfw"},
    {"name": "OpenTTD", "url": "https://www.openttd.org/", "rating": "sfw"},
    {"name": "0hh1", "url": "https://0hh1.com/", "rating": "sfw"},
    {"name": "0h n0", "url": "https://0hn0.com/", "rating": "sfw"},
    {"name": "Flow Free", "url": "https://www.bigduckgames.com/", "rating": "sfw"},
    {"name": "Little Alchemy 2", "url": "https://littlealchemy2.com/", "rating": "sfw"},
    {"name": "Infinite Craft", "url": "https://neal.fun/infinite-craft/", "rating": "sfw"},
    {"name": "Stimulation Clicker", "url": "https://neal.fun/stimulation-clicker/", "rating": "sfw"},
    {"name": "The Deep Sea", "url": "https://neal.fun/deep-sea/", "rating": "sfw"},
    {"name": "Life Stats", "url": "https://neal.fun/life-stats/", "rating": "sfw"},
    {"name": "Who Was Alive", "url": "https://neal.fun/who-was-alive/", "rating": "sfw"},
    {"name": "Wonders of Street View", "url": "https://neal.fun/wonders-of-street-view/", "rating": "sfw"},
    {"name": "Space Elevator", "url": "https://neal.fun/space-elevator/", "rating": "sfw"},
    {"name": "SCP Foundation", "url": "https://scp-wiki.wikidot.com/", "rating": "dark"},
    {"name": "Backrooms Wiki", "url": "https://backrooms-wiki.wikidot.com/", "rating": "dark"},
    {"name": "Liminal Space Wiki", "url": "https://liminalspaces.fandom.com/", "rating": "dark"},
    {"name": "Cameron's World", "url": "https://www.cameronsworld.net/", "rating": "sfw"},
    {"name": "Single Serving Sites", "url": "https://singleservingsites.cool/", "rating": "sfw"},
    {"name": "The Black Vault", "url": "https://www.theblackvault.com/", "rating": "dark"},
    {"name": "CIA Reading Room", "url": "https://www.cia.gov/readingroom/", "rating": "dark"},
    {"name": "FBI Vault", "url": "https://vault.fbi.gov/", "rating": "dark"},
    {"name": "NSA Cryptologic Museum", "url": "https://www.nsa.gov/museum", "rating": "dark"},
    {"name": "National Archives CIA Records", "url": "https://www.archives.gov/research/intelligence/cia", "rating": "dark"},
    {"name": "National Archives Catalog", "url": "https://catalog.archives.gov/", "rating": "sfw"},
    {"name": "MuckRock", "url": "https://www.muckrock.com/", "rating": "sfw"},
    {"name": "Government Attic", "url": "https://www.governmentattic.org/", "rating": "dark"},
    {"name": "NARA DocsTeach", "url": "https://www.docsteach.org/", "rating": "sfw"},
    {"name": "The Charley Project", "url": "https://charleyproject.org/", "rating": "dark"},
    {"name": "NamUs", "url": "https://namus.nij.ojp.gov/", "rating": "dark"},
    {"name": "National Center for Missing & Exploited Children", "url": "https://www.missingkids.org/", "rating": "dark"},
    {"name": "Doe Network", "url": "https://www.doenetwork.org/", "rating": "dark"},
    {"name": "Interpol Red Notices", "url": "https://www.interpol.int/How-we-work/Notices/Red-Notices/View-Red-Notices", "rating": "dark"},
    {"name": "Interpol Yellow Notices", "url": "https://www.interpol.int/How-we-work/Notices/Yellow-Notices/View-Yellow-Notices", "rating": "dark"},
    {"name": "Web Sleuths", "url": "https://websleuths.com/", "rating": "dark"},
    {"name": "Unsolved Mysteries", "url": "https://unsolved.com/", "rating": "dark"},
    {"name": "FBI Crime Data Explorer", "url": "https://cde.ucr.cjis.gov/", "rating": "dark"},
    {"name": "FBI Crime Data API", "url": "https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/home", "rating": "dark"},
    {"name": "Cold Case Coalition", "url": "https://coldcasecoalition.org/", "rating": "dark"},
    {"name": "Murder Accountability Project", "url": "https://www.murderdata.org/", "rating": "dark"},
    {"name": "Radford Serial Killer Database", "url": "https://maamodt.asp.radford.edu/", "rating": "dark"},
    {"name": "Murderpedia", "url": "https://murderpedia.org/", "rating": "dark"},
    {"name": "Atlas Obscura Dark History", "url": "https://www.atlasobscura.com/", "rating": "dark"},
    {"name": "Wikileaks", "url": "https://wikileaks.org/", "rating": "dark"},
    {"name": "Declassified UK", "url": "https://declassifieduk.org/", "rating": "dark"},
    {"name": "The National Security Archive", "url": "https://nsarchive.gwu.edu/", "rating": "dark"},
    {"name": "Wilson Center Digital Archive", "url": "https://digitalarchive.wilsoncenter.org/", "rating": "dark"},
    {"name": "Cold War International History Project", "url": "https://www.wilsoncenter.org/program/cold-war-international-history-project", "rating": "dark"},
    {"name": "Digital Public Library of America", "url": "https://dp.la/", "rating": "sfw"},
    {"name": "Digital Bodleian", "url": "https://digital.bodleian.ox.ac.uk/", "rating": "sfw"},
    {"name": "Wellcome Collection", "url": "https://wellcomecollection.org/", "rating": "sfw"},
    {"name": "Museum of Hoaxes", "url": "https://hoaxes.org/", "rating": "sfw"},
    {"name": "Museum of Fear", "url": "https://www.museumoffear.com/", "rating": "dark"},
    {"name": "Disaster Archive", "url": "https://www.disastercity.info/", "rating": "dark"},
    {"name": "Volcano Discovery", "url": "https://www.volcanodiscovery.com/", "rating": "dark"},
    {"name": "USGS Earthquake Hazards", "url": "https://earthquake.usgs.gov/", "rating": "dark"},
    {"name": "EMSC Earthquakes", "url": "https://www.emsc-csem.org/", "rating": "dark"},
    {"name": "Volcano Live", "url": "https://volcanoes.usgs.gov/", "rating": "dark"},
    {"name": "Global Incident Map", "url": "https://www.globalincidentmap.com/", "rating": "dark"},
    {"name": "Aviation Safety Network", "url": "https://aviation-safety.net/", "rating": "dark"},
    {"name": "Forensic Architecture", "url": "https://forensic-architecture.org/", "rating": "dark"},
    {"name": "The Internet Archive", "url": "https://archive.org/", "rating": "sfw"},
    {"name": "Wayback Machine", "url": "https://web.archive.org/", "rating": "sfw"},
    {"name": "Old Web Today", "url": "https://oldweb.today/", "rating": "sfw"},
    {"name": "Time Travel", "url": "https://timetravel.mementoweb.org/", "rating": "sfw"},
    {"name": "The Deleted City", "url": "https://the-deleted-city.com/", "rating": "dark"},
    {"name": "Dead Malls", "url": "https://deadmalls.com/", "rating": "dark"},
    {"name": "Liminal Gallery", "url": "https://www.liminalgallery.com/", "rating": "dark"},
    {"name": "Liminal Archives", "url": "https://liminalarchives.com/", "rating": "dark"},
    {"name": "Forgotten Spaces", "url": "https://forgotten.space/", "rating": "dark"},
    {"name": "Abandoned Places", "url": "https://www.abandonedspaces.com/", "rating": "dark"},
    {"name": "Abandoned Kansai", "url": "https://abandonedkansai.com/", "rating": "dark"},
    {"name": "Ghosts of DC", "url": "https://ghostsofdc.org/", "rating": "dark"},
    {"name": "Ghost Story Society", "url": "https://www.ghoststorysociety.com/", "rating": "dark"},
    {"name": "Haunted Rooms", "url": "https://www.hauntedrooms.co.uk/", "rating": "dark"},
    {"name": "The Shadowlands", "url": "https://theshadowlands.net/", "rating": "dark"},
    {"name": "Ghostvillage", "url": "https://www.ghostvillage.com/", "rating": "dark"},
    {"name": "Creepy Catalog", "url": "https://creepycatalog.com/", "rating": "dark"},
    {"name": "Creepypasta Wiki", "url": "https://creepypasta.fandom.com/", "rating": "dark"},
    {"name": "The SCP Foundation Database", "url": "https://scp-wiki.wikidot.com/scp-series", "rating": "dark"},
    {"name": "SCP Explained", "url": "https://scp-explained.wikidot.com/", "rating": "dark"},
    {"name": "Analog Archives", "url": "https://analog-horror.fandom.com/", "rating": "dark"},
    {"name": "Local 58", "url": "https://local58.tv/", "rating": "dark"},
    {"name": "Gemini Home Entertainment", "url": "https://geminihomeentertainment.fandom.com/", "rating": "dark"},
    {"name": "The Mandela Catalogue", "url": "https://mandela-catalogue.fandom.com/", "rating": "dark"},
    {"name": "Mysteries Unexplained", "url": "https://mysteriesunexplained.com/", "rating": "dark"},
    {"name": "Fortean Times", "url": "https://www.forteantimes.com/", "rating": "dark"},
    {"name": "Mysterious Universe", "url": "https://mysteriousuniverse.org/", "rating": "dark"},
    {"name": "Strange Sounds", "url": "https://strangesounds.org/", "rating": "dark"},
    {"name": "Forgotten Files", "url": "https://www.forgotten-books.com/", "rating": "sfw"},
    {"name": "NASA", "url": "https://www.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Science", "url": "https://science.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Eyes", "url": "https://eyes.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Eyes on the Solar System", "url": "https://eyes.nasa.gov/apps/solar-system/", "rating": "sfw"},
    {"name": "NASA Eyes on Exoplanets", "url": "https://eyes.nasa.gov/apps/exo/", "rating": "sfw"},
    {"name": "NASA Eyes on Asteroids", "url": "https://eyes.nasa.gov/apps/asteroids/", "rating": "sfw"},
    {"name": "NASA Worldview", "url": "https://worldview.earthdata.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Image and Video Library", "url": "https://images.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Visible Earth", "url": "https://visibleearth.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Earth Observatory", "url": "https://earthobservatory.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Climate", "url": "https://climate.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Space Place", "url": "https://spaceplace.nasa.gov/", "rating": "sfw"},
    {"name": "NASA JPL", "url": "https://www.jpl.nasa.gov/", "rating": "sfw"},
    {"name": "NASA Solar System Exploration", "url": "https://solarsystem.nasa.gov/", "rating": "sfw"},
    {"name": "James Webb Space Telescope", "url": "https://webbtelescope.org/", "rating": "sfw"},
    {"name": "ESA", "url": "https://www.esa.int/", "rating": "sfw"},
    {"name": "ESA Hubble", "url": "https://esahubble.org/", "rating": "sfw"},
    {"name": "ESA Kids", "url": "https://www.esa.int/kids/en/home", "rating": "sfw"},
    {"name": "Space Telescope Science Institute", "url": "https://www.stsci.edu/", "rating": "sfw"},
    {"name": "Spaceflight Now", "url": "https://spaceflightnow.com/", "rating": "sfw"},
    {"name": "Rocket Lab", "url": "https://www.rocketlabusa.com/", "rating": "sfw"},
    {"name": "SpaceX", "url": "https://www.spacex.com/", "rating": "sfw"},
    {"name": "Blue Origin", "url": "https://www.blueorigin.com/", "rating": "sfw"},
    {"name": "JAXA", "url": "https://global.jaxa.jp/", "rating": "sfw"},
    {"name": "Roscosmos", "url": "https://www.roscosmos.ru/", "rating": "sfw"},
    {"name": "ISRO", "url": "https://www.isro.gov.in/", "rating": "sfw"},
    {"name": "Breakthrough Listen", "url": "https://breakthroughinitiatives.org/initiative/1", "rating": "sfw"},
    {"name": "SETI Institute", "url": "https://www.seti.org/", "rating": "sfw"},
    {"name": "Exoplanet Archive", "url": "https://exoplanetarchive.ipac.caltech.edu/", "rating": "sfw"},
    {"name": "Sky & Telescope", "url": "https://skyandtelescope.org/", "rating": "sfw"},
    {"name": "Astronomy Magazine", "url": "https://astronomy.com/", "rating": "sfw"},
    {"name": "EarthSky", "url": "https://earthsky.org/", "rating": "sfw"},
    {"name": "Heavens Above", "url": "https://www.heavens-above.com/", "rating": "sfw"},
    {"name": "In-The-Sky.org", "url": "https://in-the-sky.org/", "rating": "sfw"},
    {"name": "CelesTrak", "url": "https://celestrak.org/", "rating": "sfw"},
    {"name": "N2YO", "url": "https://www.n2yo.com/", "rating": "sfw"},
    {"name": "Heavens Above Satellites", "url": "https://www.heavens-above.com/main.aspx", "rating": "sfw"},
    {"name": "PhET Simulations", "url": "https://phet.colorado.edu/", "rating": "sfw"},
    {"name": "Wolfram Alpha", "url": "https://www.wolframalpha.com/", "rating": "sfw"},
    {"name": "Desmos", "url": "https://www.desmos.com/", "rating": "sfw"},
    {"name": "GeoGebra", "url": "https://www.geogebra.org/", "rating": "sfw"},
    {"name": "Brilliant", "url": "https://brilliant.org/", "rating": "sfw"},
    {"name": "Khan Academy", "url": "https://www.khanacademy.org/", "rating": "sfw"},
    {"name": "CK-12", "url": "https://www.ck12.org/", "rating": "sfw"},
    {"name": "ExploreLearning Gizmos", "url": "https://www.explorelearning.com/", "rating": "sfw"},
    {"name": "Concord Consortium", "url": "https://learn.concord.org/", "rating": "sfw"},
    {"name": "Algodoo", "url": "https://www.algodoo.com/", "rating": "sfw"},
    {"name": "Falstad", "url": "https://www.falstad.com/mathphysics.html", "rating": "sfw"},
    {"name": "Paul's Online Math Notes", "url": "https://tutorial.math.lamar.edu/", "rating": "sfw"},
    {"name": "Symbolab", "url": "https://www.symbolab.com/", "rating": "sfw"},
    {"name": "Nicky Case", "url": "https://ncase.me/", "rating": "sfw"},
    {"name": "Seeing Theory", "url": "https://seeing-theory.brown.edu/", "rating": "sfw"},
    {"name": "Map of Life", "url": "https://mol.org/", "rating": "sfw"},
    {"name": "iNaturalist", "url": "https://www.inaturalist.org/", "rating": "sfw"},
    {"name": "eBird", "url": "https://ebird.org/", "rating": "sfw"},
    {"name": "All About Birds", "url": "https://www.allaboutbirds.org/", "rating": "sfw"},
    {"name": "Merlin Bird ID", "url": "https://merlin.allaboutbirds.org/", "rating": "sfw"},
    {"name": "Macaulay Library", "url": "https://www.macaulaylibrary.org/", "rating": "sfw"},
    {"name": "Explore.org", "url": "https://explore.org/livecams", "rating": "sfw"},
    {"name": "Monterey Bay Aquarium", "url": "https://www.montereybayaquarium.org/animals/live-cams", "rating": "sfw"},
    {"name": "San Diego Zoo Live Cams", "url": "https://sdzwa.org/", "rating": "sfw"},
    {"name": "Smithsonian National Zoo Cams", "url": "https://nationalzoo.si.edu/webcams", "rating": "sfw"},
    {"name": "National Aquarium Live Cams", "url": "https://aqua.org/live", "rating": "sfw"},
    {"name": "Georgia Aquarium", "url": "https://www.georgiaaquarium.org/webcam/", "rating": "sfw"},
    {"name": "Zoo Atlanta Panda Cam", "url": "https://zooatlanta.org/panda-cam/", "rating": "sfw"},
    {"name": "Houston Zoo Webcams", "url": "https://www.houstonzoo.org/webcams/", "rating": "sfw"},
    {"name": "Hawaiian Monk Seal Research Program", "url": "https://monkseal.ku.edu/", "rating": "sfw"},
    {"name": "NOAA", "url": "https://www.noaa.gov/", "rating": "sfw"},
    {"name": "NOAA Ocean Service", "url": "https://oceanservice.noaa.gov/", "rating": "sfw"},
    {"name": "NOAA Weather", "url": "https://www.weather.gov/", "rating": "sfw"},
    {"name": "USGS", "url": "https://www.usgs.gov/", "rating": "sfw"},
    {"name": "USGS Water Data", "url": "https://waterdata.usgs.gov/nwis", "rating": "sfw"},
    {"name": "National Hurricane Center", "url": "https://www.nhc.noaa.gov/", "rating": "sfw"},
    {"name": "Tropical Tidbits", "url": "https://www.tropicaltidbits.com/", "rating": "sfw"},
    {"name": "Windy", "url": "https://www.windy.com/", "rating": "sfw"},
    {"name": "Ventusky", "url": "https://www.ventusky.com/", "rating": "sfw"},
    {"name": "Blitzortung", "url": "https://www.blitzortung.org/", "rating": "sfw"},
    {"name": "World Air Quality Index", "url": "https://waqi.info/", "rating": "sfw"},
    {"name": "PurpleAir", "url": "https://map.purpleair.com/", "rating": "sfw"},
    {"name": "IQAir", "url": "https://www.iqair.com/", "rating": "sfw"},
    {"name": "Global Forest Watch", "url": "https://www.globalforestwatch.org/", "rating": "sfw"},
    {"name": "GBIF", "url": "https://www.gbif.org/", "rating": "sfw"},
    {"name": "Biodiversity Heritage Library", "url": "https://www.biodiversitylibrary.org/", "rating": "sfw"},
    {"name": "Catalogue of Life", "url": "https://www.catalogueoflife.org/", "rating": "sfw"},
    {"name": "FishBase", "url": "https://www.fishbase.se/", "rating": "sfw"},
    {"name": "Reptile Database", "url": "https://reptile-database.reptarium.cz/", "rating": "sfw"},
    {"name": "Mushroom Observer", "url": "https://mushroomobserver.org/", "rating": "sfw"},
    {"name": "World Spider Catalog", "url": "https://wsc.nmbe.ch/", "rating": "sfw"},
    {"name": "Wikipedia", "url": "https://www.wikipedia.org/", "rating": "sfw"},
    {"name": "Wikipedia Random", "url": "https://en.wikipedia.org/wiki/Special:Random", "rating": "sfw"},
    {"name": "Wikimedia Commons", "url": "https://commons.wikimedia.org/", "rating": "sfw"},
    {"name": "Wikidata", "url": "https://www.wikidata.org/", "rating": "sfw"},
    {"name": "Wikibooks", "url": "https://en.wikibooks.org/", "rating": "sfw"},
    {"name": "Wikisource", "url": "https://en.wikisource.org/", "rating": "sfw"},
    {"name": "Wikivoyage", "url": "https://www.wikivoyage.org/", "rating": "sfw"},
    {"name": "Wikiquote", "url": "https://en.wikiquote.org/", "rating": "sfw"},
    {"name": "WikiSpecies", "url": "https://species.wikimedia.org/", "rating": "sfw"},
    {"name": "Britannica", "url": "https://www.britannica.com/", "rating": "sfw"},
    {"name": "Internet Encyclopedia of Philosophy", "url": "https://iep.utm.edu/", "rating": "sfw"},
    {"name": "Stanford Encyclopedia of Philosophy", "url": "https://plato.stanford.edu/", "rating": "sfw"},
    {"name": "PhilPapers", "url": "https://philpapers.org/", "rating": "sfw"},
    {"name": "Aeon", "url": "https://aeon.co/", "rating": "sfw"},
    {"name": "Aeon Ideas", "url": "https://aeon.co/essays", "rating": "sfw"},
    {"name": "Longform", "url": "https://longform.org/", "rating": "sfw"},
    {"name": "Longreads", "url": "https://longreads.com/", "rating": "sfw"},
    {"name": "Arts & Letters Daily", "url": "https://aldaily.com/", "rating": "sfw"},
    {"name": "Letters of Note", "url": "https://lettersofnote.com/", "rating": "sfw"},
    {"name": "Futility Closet", "url": "https://www.futilitycloset.com/", "rating": "sfw"},
    {"name": "Today I Found Out", "url": "https://www.todayifoundout.com/", "rating": "sfw"},
    {"name": "Mental Floss", "url": "https://www.mentalfloss.com/", "rating": "sfw"},
    {"name": "Open Culture", "url": "https://www.openculture.com/", "rating": "sfw"},
    {"name": "Project Gutenberg", "url": "https://www.gutenberg.org/", "rating": "sfw"},
    {"name": "Open Library", "url": "https://openlibrary.org/", "rating": "sfw"},
    {"name": "LibriVox", "url": "https://librivox.org/", "rating": "sfw"},
    {"name": "ManyBooks", "url": "https://manybooks.net/", "rating": "sfw"},
    {"name": "HathiTrust", "url": "https://www.hathitrust.org/", "rating": "sfw"},
    {"name": "OpenStax", "url": "https://openstax.org/", "rating": "sfw"},
    {"name": "MIT OpenCourseWare", "url": "https://ocw.mit.edu/", "rating": "sfw"},
    {"name": "Harvard Online Learning", "url": "https://pll.harvard.edu/", "rating": "sfw"},
    {"name": "Yale Open Courses", "url": "https://oyc.yale.edu/", "rating": "sfw"},
    {"name": "Coursera", "url": "https://www.coursera.org/", "rating": "sfw"},
    {"name": "edX", "url": "https://www.edx.org/", "rating": "sfw"},
    {"name": "FutureLearn", "url": "https://www.futurelearn.com/", "rating": "sfw"},
    {"name": "OpenLearn", "url": "https://www.open.edu/openlearn/", "rating": "sfw"},
    {"name": "Saylor Academy", "url": "https://learn.saylor.org/", "rating": "sfw"},
    {"name": "FreeCodeCamp", "url": "https://www.freecodecamp.org/", "rating": "sfw"},
    {"name": "Mozilla Developer Network", "url": "https://developer.mozilla.org/", "rating": "sfw"},
    {"name": "W3Schools", "url": "https://www.w3schools.com/", "rating": "sfw"},
    {"name": "GeeksforGeeks", "url": "https://www.geeksforgeeks.org/", "rating": "sfw"},
    {"name": "OEIS", "url": "https://oeis.org/", "rating": "sfw"},
    {"name": "Wolfram MathWorld", "url": "https://mathworld.wolfram.com/", "rating": "sfw"},
    {"name": "Internet Sacred Text Archive", "url": "https://www.sacred-texts.com/", "rating": "sfw"},
    {"name": "Library of Congress", "url": "https://www.loc.gov/", "rating": "sfw"},
    {"name": "Chronicling America", "url": "https://chroniclingamerica.loc.gov/", "rating": "sfw"},
    {"name": "National Archives", "url": "https://www.archives.gov/", "rating": "sfw"},
    {"name": "Smithsonian", "url": "https://www.si.edu/", "rating": "sfw"},
    {"name": "Smithsonian Open Access", "url": "https://www.si.edu/openaccess", "rating": "sfw"},
    {"name": "Smithsonian Collections", "url": "https://collections.si.edu/", "rating": "sfw"},
    {"name": "Trove", "url": "https://trove.nla.gov.au/", "rating": "sfw"},
    {"name": "British Library", "url": "https://www.bl.uk/", "rating": "sfw"},
    {"name": "British Museum", "url": "https://www.britishmuseum.org/collection", "rating": "sfw"},
    {"name": "The Met Collection", "url": "https://www.metmuseum.org/art/collection", "rating": "sfw"},
    {"name": "National Gallery of Art", "url": "https://www.nga.gov/", "rating": "sfw"},
    {"name": "Art Institute of Chicago", "url": "https://www.artic.edu/", "rating": "sfw"},
    {"name": "Getty", "url": "https://www.getty.edu/", "rating": "sfw"},
    {"name": "Getty Search", "url": "https://search.getty.edu/gateway/landing", "rating": "sfw"},
    {"name": "Rijksmuseum", "url": "https://www.rijksmuseum.nl/en", "rating": "sfw"},
    {"name": "Musée d'Orsay", "url": "https://www.musee-orsay.fr/en", "rating": "sfw"},
    {"name": "Vatican Museums", "url": "https://www.museivaticani.va/", "rating": "sfw"},
    {"name": "Pergamon Museum Virtual", "url": "https://artsandculture.google.com/partner/pergamonmuseum", "rating": "sfw"},
    {"name": "MoMA", "url": "https://www.moma.org/", "rating": "sfw"},
    {"name": "Whitney Museum", "url": "https://whitney.org/", "rating": "sfw"},
    {"name": "Guggenheim", "url": "https://www.guggenheim.org/", "rating": "sfw"},
    {"name": "Cooper Hewitt", "url": "https://www.cooperhewitt.org/", "rating": "sfw"},
    {"name": "Science Museum", "url": "https://www.sciencemuseum.org.uk/", "rating": "sfw"},
    {"name": "Natural History Museum", "url": "https://www.nhm.ac.uk/", "rating": "sfw"},
    {"name": "Exploratorium", "url": "https://www.exploratorium.edu/", "rating": "sfw"},
    {"name": "Museum of Modern Art Digital", "url": "https://www.moma.org/collection/", "rating": "sfw"},
    {"name": "Harvard Digital Collections", "url": "https://library.harvard.edu/digital-collections", "rating": "sfw"},
    {"name": "Yale Digital Collections", "url": "https://collections.library.yale.edu/", "rating": "sfw"},
    {"name": "Princeton Digital Collections", "url": "https://dpul.princeton.edu/", "rating": "sfw"},
    {"name": "NYPL Digital Collections", "url": "https://digitalcollections.nypl.org/", "rating": "sfw"},
    {"name": "New York Public Library", "url": "https://www.nypl.org/", "rating": "sfw"},
    {"name": "World Digital Library", "url": "https://www.loc.gov/collections/world-digital-library/", "rating": "sfw"},
    {"name": "Google Arts & Culture", "url": "https://artsandculture.google.com/", "rating": "sfw"},
    {"name": "Google Experiments", "url": "https://experiments.withgoogle.com/", "rating": "sfw"},
    {"name": "Experiments Collection", "url": "https://experiments.withgoogle.com/collection/arts-culture", "rating": "sfw"},
    {"name": "The Public Domain Review", "url": "https://publicdomainreview.org/", "rating": "sfw"},
    {"name": "Public Domain Pictures", "url": "https://www.publicdomainpictures.net/", "rating": "sfw"},
    {"name": "Unsplash", "url": "https://unsplash.com/", "rating": "sfw"},
    {"name": "Wikimedia Open", "url": "https://commons.wikimedia.org/wiki/Main_Page", "rating": "sfw"},
    {"name": "ArtStation", "url": "https://www.artstation.com/", "rating": "sfw"},
    {"name": "Behance", "url": "https://www.behance.net/", "rating": "sfw"},
    {"name": "Awwwards", "url": "https://www.awwwards.com/", "rating": "sfw"},
    {"name": "CSS Design Awards", "url": "https://www.cssdesignawards.com/", "rating": "sfw"},
    {"name": "SiteInspire", "url": "https://www.siteinspire.com/", "rating": "sfw"},
    {"name": "Httpster", "url": "https://httpster.net/", "rating": "sfw"},
    {"name": "Godly", "url": "https://godly.website/", "rating": "sfw"},
    {"name": "Minimal Gallery", "url": "https://minimal.gallery/", "rating": "sfw"},
    {"name": "Land-book", "url": "https://land-book.com/", "rating": "sfw"},
    {"name": "One Page Love", "url": "https://onepagelove.com/", "rating": "sfw"},
    {"name": "Lapa Ninja", "url": "https://www.lapa.ninja/", "rating": "sfw"},
    {"name": "UI Garage", "url": "https://uigarage.net/", "rating": "sfw"},
    {"name": "Collect UI", "url": "https://collectui.com/", "rating": "sfw"},
    {"name": "Really Good Emails", "url": "https://reallygoodemails.com/", "rating": "sfw"},
    {"name": "SiteSee", "url": "https://sitesee.co/", "rating": "sfw"},
    {"name": "Dark Mode Design", "url": "https://www.darkmodedesign.com/", "rating": "sfw"},
    {"name": "A List Apart", "url": "https://alistapart.com/", "rating": "sfw"},
    {"name": "Smashing Magazine", "url": "https://www.smashingmagazine.com/", "rating": "sfw"},
    {"name": "Codrops", "url": "https://tympanus.net/codrops/", "rating": "sfw"},
    {"name": "CSS-Tricks", "url": "https://css-tricks.com/", "rating": "sfw"},
    {"name": "Canva", "url": "https://www.canva.com/", "rating": "sfw"},
    {"name": "Figma", "url": "https://www.figma.com/", "rating": "sfw"},
    {"name": "Photopea", "url": "https://www.photopea.com/", "rating": "sfw"},
    {"name": "Pixlr", "url": "https://pixlr.com/", "rating": "sfw"},
    {"name": "Krita", "url": "https://krita.org/", "rating": "sfw"},
    {"name": "GIMP", "url": "https://www.gimp.org/", "rating": "sfw"},
    {"name": "Inkscape", "url": "https://inkscape.org/", "rating": "sfw"},
    {"name": "Squoosh", "url": "https://squoosh.app/", "rating": "sfw"},
    {"name": "SVGOMG", "url": "https://jakearchibald.github.io/svgomg/", "rating": "sfw"},
    {"name": "Excalidraw", "url": "https://excalidraw.com/", "rating": "sfw"},
    {"name": "diagrams.net", "url": "https://app.diagrams.net/", "rating": "sfw"},
    {"name": "Miro", "url": "https://miro.com/", "rating": "sfw"},
    {"name": "Whimsical", "url": "https://whimsical.com/", "rating": "sfw"},
    {"name": "FigJam", "url": "https://www.figma.com/figjam/", "rating": "sfw"},
    {"name": "Coolors", "url": "https://coolors.co/", "rating": "sfw"},
    {"name": "Adobe Color", "url": "https://color.adobe.com/", "rating": "sfw"},
    {"name": "Color Hunt", "url": "https://colorhunt.co/", "rating": "sfw"},
    {"name": "Randoma11y", "url": "https://randoma11y.com/", "rating": "sfw"},
    {"name": "TinyColor", "url": "https://www.tinycolor.org/", "rating": "sfw"},
    {"name": "Paletton", "url": "https://paletton.com/", "rating": "sfw"},
    {"name": "Adobe Fonts", "url": "https://fonts.adobe.com/", "rating": "sfw"},
    {"name": "Google Fonts", "url": "https://fonts.google.com/", "rating": "sfw"},
    {"name": "Font Squirrel", "url": "https://www.fontsquirrel.com/", "rating": "sfw"},
    {"name": "DaFont", "url": "https://www.dafont.com/", "rating": "sfw"},
    {"name": "Fontjoy", "url": "https://fontjoy.com/", "rating": "sfw"},
    {"name": "Typewolf", "url": "https://www.typewolf.com/", "rating": "sfw"},
    {"name": "Type Scale", "url": "https://typescale.com/", "rating": "sfw"},
    {"name": "Responsively", "url": "https://responsively.app/", "rating": "sfw"},
    {"name": "Tiny Helpers", "url": "https://tiny-helpers.dev/", "rating": "sfw"},
    {"name": "Devhints", "url": "https://devhints.io/", "rating": "sfw"},
    {"name": "CSS Gradient", "url": "https://cssgradient.io/", "rating": "sfw"},
    {"name": "Clippy", "url": "https://bennettfeely.com/clippy/", "rating": "sfw"},
    {"name": "Cubic Bezier", "url": "https://cubic-bezier.com/", "rating": "sfw"},
    {"name": "Haikei", "url": "https://app.haikei.app/", "rating": "sfw"},
    {"name": "Get Waves", "url": "https://getwaves.io/", "rating": "sfw"},
    {"name": "Hero Patterns", "url": "https://heropatterns.com/", "rating": "sfw"},
    {"name": "Mesh Gradients", "url": "https://meshgradient.com/", "rating": "sfw"},
    {"name": "Trianglify", "url": "https://trianglify.io/", "rating": "sfw"},
    {"name": "PatternPad", "url": "https://patternpad.com/", "rating": "sfw"},
    {"name": "Dither It", "url": "https://ditherit.com/", "rating": "sfw"},
    {"name": "PhotoMosh", "url": "https://photomosh.com/", "rating": "sfw"},
    {"name": "Doodad", "url": "https://www.doodad.dev/", "rating": "sfw"},
    {"name": "Blobs", "url": "https://blobs.app/", "rating": "sfw"},
    {"name": "Noise", "url": "https://noises.online/", "rating": "sfw"},
    {"name": "XKCD", "url": "https://xkcd.com/", "rating": "sfw"},
    {"name": "SMBC Comics", "url": "https://www.smbc-comics.com/", "rating": "sfw"},
    {"name": "Cyanide & Happiness", "url": "https://explosm.net/", "rating": "sfw"},
    {"name": "The Perry Bible Fellowship", "url": "https://pbfcomics.com/", "rating": "sfw"},
    {"name": "Loading Artist", "url": "https://loadingartist.com/", "rating": "sfw"},
    {"name": "Zen Pencils", "url": "https://www.zenpencils.com/", "rating": "sfw"},
    {"name": "Poorly Drawn Lines", "url": "https://poorlydrawnlines.com/", "rating": "sfw"},
    {"name": "Dinosaur Comics", "url": "https://www.qwantz.com/", "rating": "sfw"},
    {"name": "The Awkward Yeti", "url": "https://theawkwardyeti.com/", "rating": "sfw"},
    {"name": "Penny Arcade", "url": "https://www.penny-arcade.com/", "rating": "sfw"},
    {"name": "Homestuck", "url": "https://www.homestuck.com/", "rating": "sfw"},
    {"name": "Webcomic Name", "url": "https://webcomicname.com/", "rating": "sfw"},
    {"name": "Three Panel Soul", "url": "https://www.threepanelsoul.com/", "rating": "sfw"},
    {"name": "Saturday Morning Breakfast Cereal Science", "url": "https://www.smbc-comics.com/comic/science", "rating": "sfw"},
    {"name": "Neocities", "url": "https://neocities.org/", "rating": "sfw"},
    {"name": "SpaceHey", "url": "https://spacehey.com/", "rating": "sfw"},
    {"name": "Are.na", "url": "https://www.are.na/", "rating": "sfw"},
    {"name": "Cargo", "url": "https://cargo.site/", "rating": "sfw"},
    {"name": "Colossal", "url": "https://www.thisiscolossal.com/", "rating": "sfw"},
    {"name": "It's Nice That", "url": "https://www.itsnicethat.com/", "rating": "sfw"},
    {"name": "Designboom", "url": "https://www.designboom.com/", "rating": "sfw"},
    {"name": "Dezeen", "url": "https://www.dezeen.com/", "rating": "sfw"},
    {"name": "The Creative Independent", "url": "https://thecreativeindependent.com/", "rating": "sfw"},
    {"name": "Google Maps", "url": "https://maps.google.com/", "rating": "sfw"},
    {"name": "Google Earth", "url": "https://earth.google.com/web/", "rating": "sfw"},
    {"name": "OpenStreetMap", "url": "https://www.openstreetmap.org/", "rating": "sfw"},
    {"name": "Mapillary", "url": "https://www.mapillary.com/", "rating": "sfw"},
    {"name": "City Walks Live", "url": "https://citywalks.live/", "rating": "sfw"},
    {"name": "Drive & Listen", "url": "https://driveandlisten.app/", "rating": "sfw"},
    {"name": "Virtual Vacation", "url": "https://virtualvacation.us/", "rating": "sfw"},
    {"name": "GeoSpy", "url": "https://geospy.ai/", "rating": "sfw"},
    {"name": "The True Size Of", "url": "https://www.thetruesize.com/", "rating": "sfw"},
    {"name": "GeaCron", "url": "https://geacron.com/", "rating": "sfw"},
    {"name": "Ancient Earth Globe", "url": "https://dinosaurpictures.org/ancient-earth#240", "rating": "sfw"},
    {"name": "Notable People Map", "url": "https://tjukanovt.github.io/notable-people", "rating": "sfw"},
    {"name": "Atlas of the Universe", "url": "https://www.atlasoftheuniverse.com/", "rating": "sfw"},
    {"name": "FlightAware", "url": "https://www.flightaware.com/", "rating": "sfw"},
    {"name": "Plane Finder", "url": "https://planefinder.net/", "rating": "sfw"},
    {"name": "ADS-B Exchange", "url": "https://globe.adsbexchange.com/", "rating": "sfw"},
    {"name": "OpenSky Network", "url": "https://opensky-network.org/", "rating": "sfw"},
    {"name": "MarineTraffic", "url": "https://www.marinetraffic.com/", "rating": "sfw"},
    {"name": "VesselFinder", "url": "https://www.vesselfinder.com/", "rating": "sfw"},
    {"name": "RainViewer", "url": "https://www.rainviewer.com/", "rating": "sfw"},
    {"name": "Map of the Internet", "url": "https://internet-map.net/", "rating": "sfw"},
    {"name": "Submarine Cable Map", "url": "https://www.submarinecablemap.com/", "rating": "sfw"},
    {"name": "Raildar", "url": "https://raildar.co.uk/", "rating": "sfw"},
    {"name": "Virtual Railfan", "url": "https://virtualrailfan.com/", "rating": "sfw"},
    {"name": "Trains Live", "url": "https://trains.fyi/", "rating": "sfw"},
    {"name": "Transitland", "url": "https://www.transit.land/", "rating": "sfw"},
    {"name": "Bikemap", "url": "https://www.bikemap.net/", "rating": "sfw"},
    {"name": "Wikiloc", "url": "https://www.wikiloc.com/", "rating": "sfw"},
    {"name": "AllTrails", "url": "https://www.alltrails.com/", "rating": "sfw"},
    {"name": "Komoot", "url": "https://www.komoot.com/", "rating": "sfw"},
    {"name": "Fatmap", "url": "https://fatmap.com/", "rating": "sfw"},
    {"name": "SummitPost", "url": "https://www.summitpost.org/", "rating": "sfw"},
    {"name": "Mountain Forecast", "url": "https://www.mountain-forecast.com/", "rating": "sfw"},
    {"name": "Skyscanner", "url": "https://www.skyscanner.com/", "rating": "sfw"},
    {"name": "Google Travel", "url": "https://www.google.com/travel/", "rating": "sfw"},
    {"name": "Rome2Rio", "url": "https://www.rome2rio.com/", "rating": "sfw"},
    {"name": "Wanderlog", "url": "https://wanderlog.com/", "rating": "sfw"},
    {"name": "Atlas Obscura Places", "url": "https://www.atlasobscura.com/places", "rating": "sfw"},
    {"name": "Culture Trip", "url": "https://theculturetrip.com/", "rating": "sfw"},
    {"name": "Roadtrippers", "url": "https://roadtrippers.com/", "rating": "sfw"},
    {"name": "Atlas of Wonders", "url": "https://www.atlasofwonders.com/", "rating": "sfw"},
    {"name": "Virtual Tour Map", "url": "https://www.virtualtourist.com/", "rating": "sfw"},
    {"name": "360 Cities", "url": "https://www.360cities.net/", "rating": "sfw"},
    {"name": "AirPano", "url": "https://www.airpano.com/", "rating": "sfw"},
    {"name": "RoundMe", "url": "https://roundme.com/", "rating": "sfw"},
    {"name": "Matterport", "url": "https://matterport.com/", "rating": "sfw"},
    {"name": "Kuula", "url": "https://kuula.co/", "rating": "sfw"},
    {"name": "Streetviewfun", "url": "https://www.streetviewfun.com/", "rating": "sfw"},
    {"name": "Seterra", "url": "https://www.seterra.com/", "rating": "sfw"},
    {"name": "Geography Games", "url": "https://world-geography-games.com/", "rating": "sfw"},
    {"name": "World Map", "url": "https://www.mapsofindia.com/world-map/", "rating": "sfw"},
    {"name": "Nations Online", "url": "https://www.nationsonline.org/oneworld/", "rating": "sfw"},
    {"name": "World Population Review", "url": "https://worldpopulationreview.com/", "rating": "sfw"},
    {"name": "PopulationPyramid", "url": "https://www.populationpyramid.net/", "rating": "sfw"},
    {"name": "Worldometers", "url": "https://www.worldometers.info/", "rating": "sfw"},
    {"name": "Gapminder", "url": "https://www.gapminder.org/", "rating": "sfw"},
    {"name": "Dollar Street", "url": "https://www.gapminder.org/dollar-street/", "rating": "sfw"},
    {"name": "Information is Beautiful", "url": "https://informationisbeautiful.net/", "rating": "sfw"},
    {"name": "FlowingData", "url": "https://flowingdata.com/", "rating": "sfw"},
    {"name": "Visual Capitalist", "url": "https://www.visualcapitalist.com/", "rating": "sfw"},
    {"name": "Spurious Correlations", "url": "https://www.tylervigen.com/spurious-correlations", "rating": "sfw"},
    {"name": "Data USA", "url": "https://datausa.io/", "rating": "sfw"},
    {"name": "Census Business Builder", "url": "https://www.census.gov/data/data-tools/cbb.html", "rating": "sfw"},
    {"name": "Data Commons", "url": "https://datacommons.org/", "rating": "sfw"},
    {"name": "OECD Data", "url": "https://data.oecd.org/", "rating": "sfw"},
    {"name": "World Bank Data", "url": "https://data.worldbank.org/", "rating": "sfw"},
    {"name": "UN Statistics", "url": "https://unstats.un.org/", "rating": "sfw"},
    {"name": "Trading Economics", "url": "https://tradingeconomics.com/", "rating": "sfw"},
    {"name": "Numbeo", "url": "https://www.numbeo.com/", "rating": "sfw"},
    {"name": "Expatistan", "url": "https://www.expatistan.com/", "rating": "sfw"},
    {"name": "ChatGPT", "url": "https://chatgpt.com/", "rating": "sfw"},
    {"name": "Claude", "url": "https://claude.ai/", "rating": "sfw"},
    {"name": "Gemini", "url": "https://gemini.google.com/", "rating": "sfw"},
    {"name": "Perplexity", "url": "https://www.perplexity.ai/", "rating": "sfw"},
    {"name": "Microsoft Copilot", "url": "https://copilot.microsoft.com/", "rating": "sfw"},
    {"name": "Hugging Face", "url": "https://huggingface.co/", "rating": "sfw"},
    {"name": "Replicate", "url": "https://replicate.com/", "rating": "sfw"},
    {"name": "Hugging Face Spaces", "url": "https://huggingface.co/spaces", "rating": "sfw"},
    {"name": "TensorFlow", "url": "https://www.tensorflow.org/", "rating": "sfw"},
    {"name": "PyTorch", "url": "https://pytorch.org/", "rating": "sfw"},
    {"name": "Kaggle", "url": "https://www.kaggle.com/", "rating": "sfw"},
    {"name": "Google Colab", "url": "https://colab.research.google.com/", "rating": "sfw"},
    {"name": "Observable", "url": "https://observablehq.com/", "rating": "sfw"},
    {"name": "JSFiddle", "url": "https://jsfiddle.net/", "rating": "sfw"},
    {"name": "Replit", "url": "https://replit.com/", "rating": "sfw"},
    {"name": "Stack Overflow", "url": "https://stackoverflow.com/", "rating": "sfw"},
    {"name": "GitHub", "url": "https://github.com/", "rating": "sfw"},
    {"name": "GitLab", "url": "https://gitlab.com/", "rating": "sfw"},
    {"name": "Bitbucket", "url": "https://bitbucket.org/", "rating": "sfw"},
    {"name": "Sourcegraph", "url": "https://sourcegraph.com/", "rating": "sfw"},
    {"name": "CodeSandbox", "url": "https://codesandbox.io/", "rating": "sfw"},
    {"name": "StackBlitz", "url": "https://stackblitz.com/", "rating": "sfw"},
    {"name": "Vercel", "url": "https://vercel.com/", "rating": "sfw"},
    {"name": "Netlify", "url": "https://www.netlify.com/", "rating": "sfw"},
    {"name": "Cloudflare", "url": "https://www.cloudflare.com/", "rating": "sfw"},
    {"name": "DigitalOcean", "url": "https://www.digitalocean.com/", "rating": "sfw"},
    {"name": "AWS", "url": "https://aws.amazon.com/", "rating": "sfw"},
    {"name": "Google Cloud", "url": "https://cloud.google.com/", "rating": "sfw"},
    {"name": "Azure", "url": "https://azure.microsoft.com/", "rating": "sfw"},
    {"name": "Docker Hub", "url": "https://hub.docker.com/", "rating": "sfw"},
    {"name": "npm", "url": "https://www.npmjs.com/", "rating": "sfw"},
    {"name": "Crates.io", "url": "https://crates.io/", "rating": "sfw"},
    {"name": "RubyGems", "url": "https://rubygems.org/", "rating": "sfw"},
    {"name": "Homebrew", "url": "https://brew.sh/", "rating": "sfw"},
    {"name": "Can I Use", "url": "https://caniuse.com/", "rating": "sfw"},
    {"name": "HTTP Cats", "url": "https://http.cat/", "rating": "sfw"},
    {"name": "HTTP Status Dogs", "url": "https://http.dog/", "rating": "sfw"},
    {"name": "JSONPlaceholder", "url": "https://jsonplaceholder.typicode.com/", "rating": "sfw"},
    {"name": "JSON Crack", "url": "https://jsoncrack.com/", "rating": "sfw"},
    {"name": "JSON Formatter", "url": "https://jsonformatter.org/", "rating": "sfw"},
    {"name": "Regex101", "url": "https://regex101.com/", "rating": "sfw"},
    {"name": "Regexr", "url": "https://regexr.com/", "rating": "sfw"},
    {"name": "DevDocs", "url": "https://devdocs.io/", "rating": "sfw"},
    {"name": "Dash for Developers", "url": "https://kapeli.com/dash", "rating": "sfw"},
    {"name": "ExplainShell", "url": "https://explainshell.com/", "rating": "sfw"},
    {"name": "Linux Journey", "url": "https://linuxjourney.com/", "rating": "sfw"},
    {"name": "OverTheWire", "url": "https://overthewire.org/", "rating": "sfw"},
    {"name": "Hack The Box", "url": "https://www.hackthebox.com/", "rating": "sfw"},
    {"name": "TryHackMe", "url": "https://tryhackme.com/", "rating": "sfw"},
    {"name": "CyberChef", "url": "https://gchq.github.io/CyberChef/", "rating": "sfw"},
    {"name": "Base64 Guru", "url": "https://base64.guru/", "rating": "sfw"},
    {"name": "dCode", "url": "https://www.dcode.fr/", "rating": "sfw"},
    {"name": "URL Decode", "url": "https://www.urldecoder.org/", "rating": "sfw"},
    {"name": "What Is My IP", "url": "https://whatismyipaddress.com/", "rating": "sfw"},
    {"name": "IP Location", "url": "https://iplocation.com/", "rating": "sfw"},
    {"name": "Have I Been Pwned", "url": "https://haveibeenpwned.com/", "rating": "sfw"},
    {"name": "Mozilla Observatory", "url": "https://observatory.mozilla.org/", "rating": "sfw"},
    {"name": "SSL Labs", "url": "https://www.ssllabs.com/ssltest/", "rating": "sfw"},
    {"name": "URLVoid", "url": "https://www.urlvoid.com/", "rating": "sfw"},
    {"name": "VirusTotal", "url": "https://www.virustotal.com/", "rating": "sfw"},
    {"name": "Is It Down Right Now", "url": "https://www.isitdownrightnow.com/", "rating": "sfw"},
    {"name": "Down for Everyone or Just Me", "url": "https://downforeveryoneorjustme.com/", "rating": "sfw"},
    {"name": "UptimeRobot", "url": "https://uptimerobot.com/", "rating": "sfw"},
    {"name": "Browserling", "url": "https://www.browserling.com/", "rating": "sfw"},
    {"name": "Smallpdf", "url": "https://smallpdf.com/", "rating": "sfw"},
    {"name": "iLovePDF", "url": "https://www.ilovepdf.com/", "rating": "sfw"},
    {"name": "CloudConvert", "url": "https://cloudconvert.com/", "rating": "sfw"},
    {"name": "Convertio", "url": "https://convertio.co/", "rating": "sfw"},
    {"name": "TinyWow", "url": "https://tinywow.com/", "rating": "sfw"},
    {"name": "Remove.bg", "url": "https://www.remove.bg/", "rating": "sfw"},
    {"name": "Cleanup Pictures", "url": "https://cleanup.pictures/", "rating": "sfw"},
    {"name": "Upscayl", "url": "https://upscayl.org/", "rating": "sfw"},
    {"name": "TinyPNG", "url": "https://tinypng.com/", "rating": "sfw"},
    {"name": "Lorem Picsum", "url": "https://picsum.photos/", "rating": "sfw"},
    {"name": "DiceBear", "url": "https://www.dicebear.com/", "rating": "sfw"},
    {"name": "RoboHash", "url": "https://robohash.org/", "rating": "sfw"},
    {"name": "This Person Does Not Exist", "url": "https://thispersondoesnotexist.com/", "rating": "sfw"},
    {"name": "This Cat Does Not Exist", "url": "https://thiscatdoesnotexist.com/", "rating": "sfw"},
    {"name": "This Waifu Does Not Exist", "url": "https://www.thiswaifudoesnotexist.net/", "rating": "sfw"},
    {"name": "This House Does Not Exist", "url": "https://thishousedoesnotexist.org/", "rating": "sfw"},
    {"name": "This City Does Not Exist", "url": "https://thiscitydoesnotexist.com/", "rating": "sfw"},
    {"name": "This Resume Does Not Exist", "url": "https://thisresumedoesnotexist.com/", "rating": "sfw"},
    {"name": "This Website Will Self-Destruct", "url": "https://thiswebsitewillselfdestruct.com/", "rating": "sfw"},
    {"name": "FutureMe", "url": "https://www.futureme.org/", "rating": "sfw"},
    {"name": "LanguageTool", "url": "https://languagetool.org/", "rating": "sfw"},
    {"name": "Grammarly", "url": "https://www.grammarly.com/", "rating": "sfw"},
    {"name": "DeepL", "url": "https://www.deepl.com/", "rating": "sfw"},
    {"name": "Google Translate", "url": "https://translate.google.com/", "rating": "sfw"},
    {"name": "WordReference", "url": "https://www.wordreference.com/", "rating": "sfw"},
    {"name": "Linguee", "url": "https://www.linguee.com/", "rating": "sfw"},
    {"name": "Forvo", "url": "https://forvo.com/", "rating": "sfw"},
    {"name": "YouGlish", "url": "https://youglish.com/", "rating": "sfw"},
    {"name": "Visuwords", "url": "https://visuwords.com/", "rating": "sfw"},
    {"name": "OneLook", "url": "https://www.onelook.com/", "rating": "sfw"},
    {"name": "Datamuse", "url": "https://www.datamuse.com/", "rating": "sfw"},
    {"name": "The Free Dictionary", "url": "https://www.thefreedictionary.com/", "rating": "sfw"},
    {"name": "Dictionary.com", "url": "https://www.dictionary.com/", "rating": "sfw"},
    {"name": "Merriam-Webster", "url": "https://www.merriam-webster.com/", "rating": "sfw"},
    {"name": "Thesaurus.com", "url": "https://www.thesaurus.com/", "rating": "sfw"},
    {"name": "Etymonline", "url": "https://www.etymonline.com/", "rating": "sfw"},
    {"name": "YouTube", "url": "https://www.youtube.com/", "rating": "sfw"},
    {"name": "Vimeo", "url": "https://vimeo.com/", "rating": "sfw"},
    {"name": "TED", "url": "https://www.ted.com/", "rating": "sfw"},
    {"name": "TED Talks", "url": "https://www.ted.com/talks", "rating": "sfw"},
    {"name": "PBS", "url": "https://www.pbs.org/", "rating": "sfw"},
    {"name": "NPR", "url": "https://www.npr.org/", "rating": "sfw"},
    {"name": "BBC Sounds", "url": "https://www.bbc.co.uk/sounds", "rating": "sfw"},
    {"name": "BBC Archive", "url": "https://www.bbc.co.uk/archive", "rating": "sfw"},
    {"name": "Radio Paradise", "url": "https://radioparadise.com/", "rating": "sfw"},
    {"name": "MyTuner", "url": "https://mytuner-radio.com/", "rating": "sfw"},
    {"name": "TuneIn", "url": "https://tunein.com/", "rating": "sfw"},
    {"name": "KCRW", "url": "https://www.kcrw.com/", "rating": "sfw"},
    {"name": "WFMU", "url": "https://wfmu.org/", "rating": "sfw"},
    {"name": "WNYC", "url": "https://www.wnyc.org/", "rating": "sfw"},
    {"name": "WFYI", "url": "https://www.wfyi.org/", "rating": "sfw"},
    {"name": "KEXP Live", "url": "https://www.kexp.org/live/", "rating": "sfw"},
    {"name": "Freesound", "url": "https://freesound.org/", "rating": "sfw"},
    {"name": "Openverse Audio", "url": "https://openverse.org/", "rating": "sfw"},
    {"name": "Jamendo", "url": "https://www.jamendo.com/", "rating": "sfw"},
    {"name": "Bandcamp", "url": "https://bandcamp.com/", "rating": "sfw"},
    {"name": "Mixcloud", "url": "https://www.mixcloud.com/", "rating": "sfw"},
    {"name": "Audius", "url": "https://audius.co/", "rating": "sfw"},
    {"name": "Last.fm", "url": "https://www.last.fm/", "rating": "sfw"},
    {"name": "MusicBrainz", "url": "https://musicbrainz.org/", "rating": "sfw"},
    {"name": "Discogs", "url": "https://www.discogs.com/", "rating": "sfw"},
    {"name": "AllMusic", "url": "https://www.allmusic.com/", "rating": "sfw"},
    {"name": "Rate Your Music", "url": "https://rateyourmusic.com/", "rating": "sfw"},
    {"name": "Every Noise at Once", "url": "https://everynoise.com/", "rating": "sfw"},
    {"name": "Setlist.fm", "url": "https://www.setlist.fm/", "rating": "sfw"},
    {"name": "Songsterr", "url": "https://www.songsterr.com/", "rating": "sfw"},
    {"name": "Ultimate Guitar", "url": "https://www.ultimate-guitar.com/", "rating": "sfw"},
    {"name": "Musipedia", "url": "https://www.musipedia.org/", "rating": "sfw"},
    {"name": "Patatap", "url": "https://patatap.com/", "rating": "sfw"},
    {"name": "Virtual Piano", "url": "https://virtualpiano.net/", "rating": "sfw"},
    {"name": "Noteflight", "url": "https://www.noteflight.com/", "rating": "sfw"},
    {"name": "Flat", "url": "https://flat.io/", "rating": "sfw"},
    {"name": "Soundtrap", "url": "https://www.soundtrap.com/", "rating": "sfw"},
    {"name": "Audiotool", "url": "https://www.audiotool.com/", "rating": "sfw"},
    {"name": "Splice", "url": "https://splice.com/", "rating": "sfw"},
    {"name": "Moises", "url": "https://moises.ai/", "rating": "sfw"},
    {"name": "AIVA", "url": "https://www.aiva.ai/", "rating": "sfw"},
    {"name": "Boomy", "url": "https://boomy.com/", "rating": "sfw"},
    {"name": "Suno", "url": "https://suno.com/", "rating": "sfw"},
    {"name": "Udio", "url": "https://www.udio.com/", "rating": "sfw"},
    {"name": "Mubert", "url": "https://mubert.com/", "rating": "sfw"},
    {"name": "LALAL.AI", "url": "https://www.lalal.ai/", "rating": "sfw"},
    {"name": "Descript", "url": "https://www.descript.com/", "rating": "sfw"},
    {"name": "Kapwing", "url": "https://www.kapwing.com/", "rating": "sfw"},
    {"name": "VEED", "url": "https://www.veed.io/", "rating": "sfw"},
    {"name": "Canva Video", "url": "https://www.canva.com/video-editor/", "rating": "sfw"},
    {"name": "Clipchamp", "url": "https://clipchamp.com/", "rating": "sfw"},
    {"name": "DaVinci Resolve", "url": "https://www.blackmagicdesign.com/products/davinciresolve", "rating": "sfw"},
    {"name": "OBS", "url": "https://obsproject.com/", "rating": "sfw"},
    {"name": "Streamlabs", "url": "https://streamlabs.com/", "rating": "sfw"},
    {"name": "Twitch", "url": "https://www.twitch.tv/", "rating": "sfw"},
    {"name": "Letterboxd", "url": "https://letterboxd.com/", "rating": "sfw"},
    {"name": "IMDb", "url": "https://www.imdb.com/", "rating": "sfw"},
    {"name": "Rotten Tomatoes", "url": "https://www.rottentomatoes.com/", "rating": "sfw"},
    {"name": "Metacritic", "url": "https://www.metacritic.com/", "rating": "sfw"},
    {"name": "TasteDive", "url": "https://tastedive.com/", "rating": "sfw"},
    {"name": "Movie-Map", "url": "https://www.movie-map.com/", "rating": "sfw"},
    {"name": "Cinetrii", "url": "https://cinetrii.com/", "rating": "sfw"},
    {"name": "FilmGrab", "url": "https://film-grab.com/", "rating": "sfw"},
    {"name": "Script Slug", "url": "https://www.scriptslug.com/", "rating": "sfw"},
    {"name": "JustWatch", "url": "https://www.justwatch.com/", "rating": "sfw"},
    {"name": "TV Tropes", "url": "https://tvtropes.org/", "rating": "sfw"},
    {"name": "Fandom", "url": "https://www.fandom.com/", "rating": "sfw"},
    {"name": "Know Your Meme", "url": "https://knowyourmeme.com/", "rating": "sfw"},
    {"name": "TV Garden", "url": "https://tv.garden/", "rating": "sfw"},
    {"name": "PlayPhrase", "url": "https://www.playphrase.me/", "rating": "sfw"},
    {"name": "Reddit", "url": "https://www.reddit.com/", "rating": "sfw"},
    {"name": "Hacker News", "url": "https://news.ycombinator.com/", "rating": "sfw"},
    {"name": "Lobsters", "url": "https://lobste.rs/", "rating": "sfw"},
    {"name": "Quora", "url": "https://www.quora.com/", "rating": "sfw"},
    {"name": "Metafilter", "url": "https://www.metafilter.com/", "rating": "sfw"},
    {"name": "Kottke", "url": "https://kottke.org/", "rating": "sfw"},
    {"name": "Boing Boing", "url": "https://boingboing.net/", "rating": "sfw"},
    {"name": "Neatorama", "url": "https://www.neatorama.com/", "rating": "sfw"},
    {"name": "Bored Panda", "url": "https://www.boredpanda.com/", "rating": "sfw"},
    {"name": "Pleated Jeans", "url": "https://pleated-jeans.com/", "rating": "sfw"},
    {"name": "The Onion", "url": "https://theonion.com/", "rating": "sfw"},
    {"name": "Everyday Carry", "url": "https://everydaycarry.com/", "rating": "sfw"},
    {"name": "Mountain of Ink", "url": "https://mountainofink.com/", "rating": "sfw"},
    {"name": "Ian's Shoelace Site", "url": "https://www.fieggen.com/shoelace/", "rating": "sfw"},
    {"name": "SkyscraperPage", "url": "https://skyscraperpage.com/", "rating": "sfw"},
    {"name": "Tokyo Toilet", "url": "https://tokyotoilet.jp/", "rating": "sfw"},
    {"name": "Consumed Today", "url": "https://consumed.today/", "rating": "sfw"},
    {"name": "Cyberdeck Cafe", "url": "https://cyberdeck.cafe/", "rating": "sfw"},
    {"name": "The Toy Zone", "url": "https://thetoyzone.com/", "rating": "sfw"},
    {"name": "This Is Why I'm Broke", "url": "https://www.thisiswhyimbroke.com/", "rating": "sfw"},
    {"name": "Odditymall", "url": "https://odditymall.com/", "rating": "sfw"},
    {"name": "Weird or Confusing", "url": "https://weirdorconfusing.com/", "rating": "sfw"},
    {"name": "Firebox", "url": "https://firebox.com/", "rating": "sfw"},
    {"name": "Archie McPhee", "url": "https://mcphee.com/", "rating": "sfw"},
    {"name": "Stuff My Dog Loves", "url": "https://stuffmydogloves.com/", "rating": "sfw"},
    {"name": "Always Judge a Book by its Cover", "url": "https://alwaysjudgeabookbyitscover.com/", "rating": "sfw"},
    {"name": "Freerice", "url": "https://freerice.com/", "rating": "sfw"},
    {"name": "GiveWell", "url": "https://www.givewell.org/", "rating": "sfw"},
    {"name": "Charity Navigator", "url": "https://www.charitynavigator.org/", "rating": "sfw"},
    {"name": "VolunteerMatch", "url": "https://www.volunteermatch.org/", "rating": "sfw"},
    {"name": "DoSomething", "url": "https://www.dosomething.org/", "rating": "sfw"},
    {"name": "Ecosia", "url": "https://www.ecosia.org/", "rating": "sfw"},
    {"name": "Khan Academy Kids", "url": "https://learn.khanacademy.org/khan-academy-kids/", "rating": "sfw"},
    {"name": "Duolingo", "url": "https://www.duolingo.com/", "rating": "sfw"},
    {"name": "Memrise", "url": "https://www.memrise.com/", "rating": "sfw"},
    {"name": "Language Transfer", "url": "https://www.languagetransfer.org/", "rating": "sfw"},
    {"name": "AnkiWeb", "url": "https://ankiweb.net/", "rating": "sfw"},
    {"name": "Quizlet", "url": "https://quizlet.com/", "rating": "sfw"},
    {"name": "Goodreads", "url": "https://www.goodreads.com/", "rating": "sfw"},
    {"name": "LibraryThing", "url": "https://www.librarything.com/", "rating": "sfw"},
    {"name": "StoryGraph", "url": "https://app.thestorygraph.com/", "rating": "sfw"},
    {"name": "Book Riot", "url": "https://bookriot.com/", "rating": "sfw"},
    {"name": "The Marginalian", "url": "https://www.themarginalian.org/", "rating": "sfw"},
    {"name": "Nautilus", "url": "https://nautil.us/", "rating": "sfw"},
    {"name": "Quanta Magazine", "url": "https://www.quantamagazine.org/", "rating": "sfw"},
    {"name": "The Pudding", "url": "https://pudding.cool/", "rating": "sfw"},
    {"name": "FiveThirtyEight", "url": "https://fivethirtyeight.com/", "rating": "sfw"},
    {"name": "ArXiv", "url": "https://arxiv.org/", "rating": "sfw"},
    {"name": "Semantic Scholar", "url": "https://www.semanticscholar.org/", "rating": "sfw"},
    {"name": "Google Scholar", "url": "https://scholar.google.com/", "rating": "sfw"},
    {"name": "CORE", "url": "https://core.ac.uk/", "rating": "sfw"},
    {"name": "OpenAlex", "url": "https://openalex.org/", "rating": "sfw"},
    {"name": "Crossref", "url": "https://www.crossref.org/", "rating": "sfw"},
    {"name": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/", "rating": "sfw"},
    {"name": "Europe PMC", "url": "https://europepmc.org/", "rating": "sfw"},
    {"name": "ClinicalTrials.gov", "url": "https://clinicaltrials.gov/", "rating": "sfw"},
    {"name": "The Happy Newspaper", "url": "https://thehappynewspaper.com/", "rating": "sfw"},
    {"name": "Random Acts of Kindness", "url": "https://www.randomactsofkindness.org/", "rating": "sfw"},
    {"name": "Action for Happiness", "url": "https://actionforhappiness.org/", "rating": "sfw"},
    {"name": "Pug in a Rug", "url": "https://puginarug.com/", "rating": "sfw"},
    {"name": "OpenPuppies", "url": "https://openpuppies.com/", "rating": "sfw"},
    {"name": "ChessTempo", "url": "https://chesstempo.com/", "rating": "sfw"},
    {"name": "Chessable", "url": "https://www.chessable.com/", "rating": "sfw"},
    {"name": "Lichess Studies", "url": "https://lichess.org/study", "rating": "sfw"},
    {"name": "The Spruce", "url": "https://www.thespruce.com/", "rating": "sfw"},
    {"name": "Serious Eats", "url": "https://www.seriouseats.com/", "rating": "sfw"},
    {"name": "Food52", "url": "https://food52.com/", "rating": "sfw"},
    {"name": "Epicurious", "url": "https://www.epicurious.com/", "rating": "sfw"},
    {"name": "Tasty", "url": "https://tasty.co/", "rating": "sfw"},
    {"name": "Taste of Home", "url": "https://www.tasteofhome.com/", "rating": "sfw"},
    {"name": "King Arthur Baking", "url": "https://www.kingarthurbaking.com/", "rating": "sfw"},
    {"name": "America's Test Kitchen", "url": "https://www.americastestkitchen.com/", "rating": "sfw"},
    {"name": "Binging with Babish", "url": "https://www.bingingwithbabish.com/", "rating": "sfw"},
    {"name": "SuperCook", "url": "https://www.supercook.com/", "rating": "sfw"},
    {"name": "Yummly", "url": "https://www.yummly.com/", "rating": "sfw"},
    {"name": "Eat Your Books", "url": "https://www.eatyourbooks.com/", "rating": "sfw"},
    {"name": "Instructables", "url": "https://www.instructables.com/", "rating": "sfw"},
    {"name": "Makezine", "url": "https://makezine.com/", "rating": "sfw"},
    {"name": "Hackaday", "url": "https://hackaday.com/", "rating": "sfw"},
    {"name": "Adafruit", "url": "https://www.adafruit.com/", "rating": "sfw"},
    {"name": "SparkFun", "url": "https://www.sparkfun.com/", "rating": "sfw"},
    {"name": "Thingiverse", "url": "https://www.thingiverse.com/", "rating": "sfw"},
    {"name": "MyMiniFactory", "url": "https://www.myminifactory.com/", "rating": "sfw"},
    {"name": "GrabCAD", "url": "https://grabcad.com/", "rating": "sfw"},
    {"name": "Sketchfab", "url": "https://sketchfab.com/", "rating": "sfw"},
    {"name": "Blender", "url": "https://www.blender.org/", "rating": "sfw"},
    {"name": "Poly Haven", "url": "https://polyhaven.com/", "rating": "sfw"},
    {"name": "AmbientCG", "url": "https://ambientcg.com/", "rating": "sfw"},
    {"name": "OpenGameArt", "url": "https://opengameart.org/", "rating": "sfw"},
    {"name": "Kenney", "url": "https://kenney.nl/", "rating": "sfw"},
    {"name": "Game-icons.net", "url": "https://game-icons.net/", "rating": "sfw"},
    {"name": "Pexels", "url": "https://www.pexels.com/", "rating": "sfw"},
    {"name": "Pixabay", "url": "https://pixabay.com/", "rating": "sfw"},
    {"name": "Burst", "url": "https://burst.shopify.com/", "rating": "sfw"},
    {"name": "Public Domain Vectors", "url": "https://publicdomainvectors.org/", "rating": "sfw"},
    {"name": "Open Clipart", "url": "https://openclipart.org/", "rating": "sfw"},
    {"name": "FreeSVG", "url": "https://freesvg.org/", "rating": "sfw"},
    {"name": "unDraw", "url": "https://undraw.co/", "rating": "sfw"},
    {"name": "Storyset", "url": "https://storyset.com/", "rating": "sfw"},
    {"name": "Humaaans", "url": "https://www.humaaans.com/", "rating": "sfw"},
    {"name": "Blush", "url": "https://blush.design/", "rating": "sfw"},
    {"name": "ManyPixels", "url": "https://www.manypixels.co/gallery", "rating": "sfw"},
    {"name": "DrawKit", "url": "https://www.drawkit.com/", "rating": "sfw"},
    {"name": "Open Doodles", "url": "https://www.opendoodles.com/", "rating": "sfw"},
    {"name": "Loose Drawing", "url": "https://loosedrawing.com/", "rating": "sfw"},
    {"name": "Emoji Kitchen", "url": "https://emojikitchen.dev/", "rating": "sfw"},
    {"name": "Emojipedia", "url": "https://emojipedia.org/", "rating": "sfw"},
    {"name": "Unicode", "url": "https://unicode.org/", "rating": "sfw"},
    {"name": "Unicode Character Search", "url": "https://www.fileformat.info/info/unicode/", "rating": "sfw"},
    {"name": "Symbola", "url": "https://www.symbola.org/", "rating": "sfw"},
    {"name": "Random.org", "url": "https://www.random.org/", "rating": "sfw"},
    {"name": "QR Code Generator", "url": "https://www.qr-code-generator.com/", "rating": "sfw"},
    {"name": "QR Code Monkey", "url": "https://www.qrcode-monkey.com/", "rating": "sfw"},
    {"name": "TinyURL", "url": "https://tinyurl.com/", "rating": "sfw"},
    {"name": "URL Shortener", "url": "https://is.gd/", "rating": "sfw"},
    {"name": "Pastebin", "url": "https://pastebin.com/", "rating": "sfw"},
    {"name": "PrivateBin", "url": "https://privatebin.net/", "rating": "sfw"},
    {"name": "JustDeleteMe", "url": "https://justdeleteme.xyz/", "rating": "sfw"},
    {"name": "Privacy Guides", "url": "https://www.privacyguides.org/", "rating": "sfw"},
    {"name": "EFF", "url": "https://www.eff.org/", "rating": "sfw"},
    {"name": "Privacy Badger", "url": "https://privacybadger.org/", "rating": "sfw"},
    {"name": "Firefox Monitor", "url": "https://monitor.firefox.com/", "rating": "sfw"},
    {"name": "The Guardian", "url": "https://www.theguardian.com/", "rating": "sfw"},
    {"name": "New York Times", "url": "https://www.nytimes.com/", "rating": "sfw"},
    {"name": "Washington Post", "url": "https://www.washingtonpost.com/", "rating": "sfw"},
    {"name": "Smithsonian Magazine", "url": "https://www.smithsonianmag.com/", "rating": "sfw"},
    {"name": "Popular Science", "url": "https://www.popsci.com/", "rating": "sfw"},
    {"name": "Popular Mechanics", "url": "https://www.popularmechanics.com/", "rating": "sfw"},
    {"name": "Scientific American", "url": "https://www.scientificamerican.com/", "rating": "sfw"},
    {"name": "Discover Magazine", "url": "https://www.discovermagazine.com/", "rating": "sfw"},
    {"name": "Live Science", "url": "https://www.livescience.com/", "rating": "sfw"},
    {"name": "New Scientist", "url": "https://www.newscientist.com/", "rating": "sfw"},
    {"name": "Science News", "url": "https://www.sciencenews.org/", "rating": "sfw"},
    {"name": "ScienceDaily", "url": "https://www.sciencedaily.com/", "rating": "sfw"},
    {"name": "Phys.org", "url": "https://phys.org/", "rating": "sfw"},
    {"name": "Britannica Kids", "url": "https://kids.britannica.com/", "rating": "sfw"},
    {"name": "TED-Ed", "url": "https://ed.ted.com/", "rating": "sfw"},
    {"name": "Crash Course", "url": "https://thecrashcourse.com/", "rating": "sfw"},
    {"name": "Veritasium", "url": "https://www.veritasium.com/", "rating": "sfw"},
    {"name": "Kurzgesagt", "url": "https://kurzgesagt.org/", "rating": "sfw"},
    {"name": "Numberphile", "url": "https://www.numberphile.com/", "rating": "sfw"},
    {"name": "Computerphile", "url": "https://www.computerphile.net/", "rating": "sfw"},
    {"name": "PBS Space Time", "url": "https://www.pbs.org/wgbh/nova/space/", "rating": "sfw"},
    {"name": "3Blue1Brown", "url": "https://www.3blue1brown.com/", "rating": "sfw"},
    {"name": "SciShow", "url": "https://scishow.com/", "rating": "sfw"},
    {"name": "Smarter Every Day", "url": "https://www.smartereveryday.com/", "rating": "sfw"},
    {"name": "Mark Rober", "url": "https://markrober.com/", "rating": "sfw"},
    {"name": "Tom Scott", "url": "https://www.tomscott.com/", "rating": "sfw"},
    {"name": "CGP Grey", "url": "https://www.cgpgrey.com/", "rating": "sfw"},
    {"name": "Technology Connections", "url": "https://www.technologyconnections.com/", "rating": "sfw"},
    {"name": "Steve Mould", "url": "https://www.stevemould.com/", "rating": "sfw"},
    {"name": "NightHawkInLight", "url": "https://www.nighthawkinlight.com/", "rating": "sfw"},
    {"name": "Scream Into the Void", "url": "https://screamintothevoid.com/", "rating": "sfw"},
    {"name": "Cat Bounce", "url": "https://cat-bounce.com/", "rating": "sfw"},
    {"name": "Eel Slap", "url": "https://eelslap.net/", "rating": "sfw"},
    {"name": "GreenGeeks Weird Websites", "url": "https://www.greengeeks.com/blog/weird-websites-to-visit-when-bored/", "rating": "sfw"},
    {"name": "Webflow Useless Websites", "url": "https://webflow.com/blog/useless-websites", "rating": "sfw"},
    {"name": "Hacker Typer", "url": "https://hackertyper.net/", "rating": "sfw"},
    {"name": "The Nicest Place on the Internet", "url": "https://thenicestplace.net/", "rating": "sfw"},
    {"name": "Is It Christmas?", "url": "https://isitchristmas.com/", "rating": "sfw"},
    {"name": "Create a Pro Website Weird Sites", "url": "https://createaprowebsite.com/weird-websites-to-visit/", "rating": "sfw"},
    {"name": "NASA Learn Science", "url": "https://science.nasa.gov/learn/learn-nasa-science/", "rating": "sfw"},
    {"name": "Nature", "url": "https://www.nature.com/", "rating": "sfw"},
    {"name": "Science", "url": "https://www.science.org/", "rating": "sfw"},
    {"name": "Cell", "url": "https://www.cell.com/", "rating": "sfw"},
    {"name": "PLOS", "url": "https://plos.org/", "rating": "sfw"},
    {"name": "BioRxiv", "url": "https://www.biorxiv.org/", "rating": "sfw"},
    {"name": "MedRxiv", "url": "https://www.medrxiv.org/", "rating": "sfw"},
    {"name": "NASA Earthdata", "url": "https://www.earthdata.nasa.gov/", "rating": "sfw"},
    {"name": "USGS Astrogeology", "url": "https://astrogeology.usgs.gov/", "rating": "sfw"},
    {"name": "USGS Maps", "url": "https://www.usgs.gov/products/maps", "rating": "sfw"},
    {"name": "Natural Earth", "url": "https://www.naturalearthdata.com/", "rating": "sfw"},
    {"name": "Mapbox", "url": "https://www.mapbox.com/", "rating": "sfw"},
    {"name": "Carto", "url": "https://carto.com/", "rating": "sfw"},
    {"name": "Leaflet", "url": "https://leafletjs.com/", "rating": "sfw"},
    {"name": "OpenLayers", "url": "https://openlayers.org/", "rating": "sfw"},
    {"name": "Cesium", "url": "https://cesium.com/platform/cesiumjs/", "rating": "sfw"},
    {"name": "Kepler.gl", "url": "https://kepler.gl/", "rating": "sfw"},
    {"name": "MapChart", "url": "https://www.mapchart.net/", "rating": "sfw"},
    {"name": "WorldMapGenerator", "url": "https://www.worldmapgenerator.com/", "rating": "sfw"},
    {"name": "Chronas", "url": "https://chronas.org/", "rating": "sfw"},
    {"name": "TimeMaps", "url": "https://timemaps.com/", "rating": "sfw"},
    {"name": "HistoryMaps", "url": "https://history-maps.com/", "rating": "sfw"},
    {"name": "History Today", "url": "https://www.historytoday.com/", "rating": "sfw"},
    {"name": "HistoryExtra", "url": "https://www.historyextra.com/", "rating": "sfw"},
    {"name": "Ancient Origins", "url": "https://www.ancient-origins.net/", "rating": "sfw"},
    {"name": "History Collection", "url": "https://historycollection.com/", "rating": "sfw"},
    {"name": "Smithsonian Transcription Center", "url": "https://transcription.si.edu/", "rating": "sfw"},
    {"name": "Foldit", "url": "https://fold.it/", "rating": "sfw"},
    {"name": "Eyewire", "url": "https://eyewire.org/", "rating": "sfw"},
    {"name": "Galaxy Zoo", "url": "https://www.zooniverse.org/projects/zookeeper/galaxy-zoo", "rating": "sfw"},
    {"name": "iNaturalist Seek", "url": "https://www.inaturalist.org/pages/seek_app", "rating": "sfw"},
    {"name": "SciStarter", "url": "https://scistarter.org/", "rating": "sfw"},
    {"name": "Citizen Science", "url": "https://www.citizenscience.gov/", "rating": "sfw"},
    {"name": "eBird Hotspots", "url": "https://ebird.org/hotspots", "rating": "sfw"},
    {"name": "Cornell Lab", "url": "https://www.birds.cornell.edu/", "rating": "sfw"},
    {"name": "Audubon", "url": "https://www.audubon.org/", "rating": "sfw"},
    {"name": "Mammal Diversity Database", "url": "https://www.mammaldiversity.org/", "rating": "sfw"},
    {"name": "Tree of Life Web Project", "url": "http://tolweb.org/tree/", "rating": "sfw"},
    {"name": "Amphibian Species of the World", "url": "https://amphibiansoftheworld.amnh.org/", "rating": "sfw"},
    {"name": "Index Fungorum", "url": "https://www.indexfungorum.org/", "rating": "sfw"},
    {"name": "MycoBank", "url": "https://www.mycobank.org/", "rating": "sfw"}
];